# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pbr/CLionProjects/ThreadSafeMemoryPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pbr/CLionProjects/ThreadSafeMemoryPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pbr/CLionProjects/ThreadSafeMemoryPool/CMakeFiles /Users/pbr/CLionProjects/ThreadSafeMemoryPool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pbr/CLionProjects/ThreadSafeMemoryPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ThreadSafeMemoryPoolLib

# Build rule for target.
ThreadSafeMemoryPoolLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThreadSafeMemoryPoolLib
.PHONY : ThreadSafeMemoryPoolLib

# fast build rule for target.
ThreadSafeMemoryPoolLib/fast:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolLib.dir/build.make CMakeFiles/ThreadSafeMemoryPoolLib.dir/build
.PHONY : ThreadSafeMemoryPoolLib/fast

#=============================================================================
# Target rules for targets named ThreadSafeMemoryPoolTests

# Build rule for target.
ThreadSafeMemoryPoolTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThreadSafeMemoryPoolTests
.PHONY : ThreadSafeMemoryPoolTests

# fast build rule for target.
ThreadSafeMemoryPoolTests/fast:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/build
.PHONY : ThreadSafeMemoryPoolTests/fast

#=============================================================================
# Target rules for targets named ThreadSafeMemoryPoolBenchmark

# Build rule for target.
ThreadSafeMemoryPoolBenchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ThreadSafeMemoryPoolBenchmark
.PHONY : ThreadSafeMemoryPoolBenchmark

# fast build rule for target.
ThreadSafeMemoryPoolBenchmark/fast:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/build.make CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/build
.PHONY : ThreadSafeMemoryPoolBenchmark/fast

#=============================================================================
# Target rules for targets named benchmark_main

# Build rule for target.
benchmark_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_main
.PHONY : benchmark_main

# fast build rule for target.
benchmark_main/fast:
	$(MAKE) -f vendor/google/benchmark/src/CMakeFiles/benchmark_main.dir/build.make vendor/google/benchmark/src/CMakeFiles/benchmark_main.dir/build
.PHONY : benchmark_main/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f vendor/google/benchmark/src/CMakeFiles/benchmark.dir/build.make vendor/google/benchmark/src/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f vendor/google/googletest/googletest/CMakeFiles/gtest_main.dir/build.make vendor/google/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f vendor/google/googletest/googletest/CMakeFiles/gtest.dir/build.make vendor/google/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/main.cpp.s
.PHONY : main.cpp.s

src/BM_MemoryPool.o: src/BM_MemoryPool.cpp.o

.PHONY : src/BM_MemoryPool.o

# target to build an object file
src/BM_MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/build.make CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/src/BM_MemoryPool.cpp.o
.PHONY : src/BM_MemoryPool.cpp.o

src/BM_MemoryPool.i: src/BM_MemoryPool.cpp.i

.PHONY : src/BM_MemoryPool.i

# target to preprocess a source file
src/BM_MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/build.make CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/src/BM_MemoryPool.cpp.i
.PHONY : src/BM_MemoryPool.cpp.i

src/BM_MemoryPool.s: src/BM_MemoryPool.cpp.s

.PHONY : src/BM_MemoryPool.s

# target to generate assembly for a file
src/BM_MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/build.make CMakeFiles/ThreadSafeMemoryPoolBenchmark.dir/src/BM_MemoryPool.cpp.s
.PHONY : src/BM_MemoryPool.cpp.s

src/Coordinates.o: src/Coordinates.cpp.o

.PHONY : src/Coordinates.o

# target to build an object file
src/Coordinates.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/src/Coordinates.cpp.o
.PHONY : src/Coordinates.cpp.o

src/Coordinates.i: src/Coordinates.cpp.i

.PHONY : src/Coordinates.i

# target to preprocess a source file
src/Coordinates.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/src/Coordinates.cpp.i
.PHONY : src/Coordinates.cpp.i

src/Coordinates.s: src/Coordinates.cpp.s

.PHONY : src/Coordinates.s

# target to generate assembly for a file
src/Coordinates.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/src/Coordinates.cpp.s
.PHONY : src/Coordinates.cpp.s

src/MemoryPool.o: src/MemoryPool.cpp.o

.PHONY : src/MemoryPool.o

# target to build an object file
src/MemoryPool.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolLib.dir/build.make CMakeFiles/ThreadSafeMemoryPoolLib.dir/src/MemoryPool.cpp.o
.PHONY : src/MemoryPool.cpp.o

src/MemoryPool.i: src/MemoryPool.cpp.i

.PHONY : src/MemoryPool.i

# target to preprocess a source file
src/MemoryPool.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolLib.dir/build.make CMakeFiles/ThreadSafeMemoryPoolLib.dir/src/MemoryPool.cpp.i
.PHONY : src/MemoryPool.cpp.i

src/MemoryPool.s: src/MemoryPool.cpp.s

.PHONY : src/MemoryPool.s

# target to generate assembly for a file
src/MemoryPool.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolLib.dir/build.make CMakeFiles/ThreadSafeMemoryPoolLib.dir/src/MemoryPool.cpp.s
.PHONY : src/MemoryPool.cpp.s

tst/BasicMemoryPoolTest.o: tst/BasicMemoryPoolTest.cpp.o

.PHONY : tst/BasicMemoryPoolTest.o

# target to build an object file
tst/BasicMemoryPoolTest.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/BasicMemoryPoolTest.cpp.o
.PHONY : tst/BasicMemoryPoolTest.cpp.o

tst/BasicMemoryPoolTest.i: tst/BasicMemoryPoolTest.cpp.i

.PHONY : tst/BasicMemoryPoolTest.i

# target to preprocess a source file
tst/BasicMemoryPoolTest.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/BasicMemoryPoolTest.cpp.i
.PHONY : tst/BasicMemoryPoolTest.cpp.i

tst/BasicMemoryPoolTest.s: tst/BasicMemoryPoolTest.cpp.s

.PHONY : tst/BasicMemoryPoolTest.s

# target to generate assembly for a file
tst/BasicMemoryPoolTest.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/BasicMemoryPoolTest.cpp.s
.PHONY : tst/BasicMemoryPoolTest.cpp.s

tst/MemoryPoolTestMultiThreading.o: tst/MemoryPoolTestMultiThreading.cpp.o

.PHONY : tst/MemoryPoolTestMultiThreading.o

# target to build an object file
tst/MemoryPoolTestMultiThreading.cpp.o:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/MemoryPoolTestMultiThreading.cpp.o
.PHONY : tst/MemoryPoolTestMultiThreading.cpp.o

tst/MemoryPoolTestMultiThreading.i: tst/MemoryPoolTestMultiThreading.cpp.i

.PHONY : tst/MemoryPoolTestMultiThreading.i

# target to preprocess a source file
tst/MemoryPoolTestMultiThreading.cpp.i:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/MemoryPoolTestMultiThreading.cpp.i
.PHONY : tst/MemoryPoolTestMultiThreading.cpp.i

tst/MemoryPoolTestMultiThreading.s: tst/MemoryPoolTestMultiThreading.cpp.s

.PHONY : tst/MemoryPoolTestMultiThreading.s

# target to generate assembly for a file
tst/MemoryPoolTestMultiThreading.cpp.s:
	$(MAKE) -f CMakeFiles/ThreadSafeMemoryPoolTests.dir/build.make CMakeFiles/ThreadSafeMemoryPoolTests.dir/tst/MemoryPoolTestMultiThreading.cpp.s
.PHONY : tst/MemoryPoolTestMultiThreading.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... ThreadSafeMemoryPoolLib"
	@echo "... ThreadSafeMemoryPoolTests"
	@echo "... ThreadSafeMemoryPoolBenchmark"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... benchmark_main"
	@echo "... benchmark"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BM_MemoryPool.o"
	@echo "... src/BM_MemoryPool.i"
	@echo "... src/BM_MemoryPool.s"
	@echo "... src/Coordinates.o"
	@echo "... src/Coordinates.i"
	@echo "... src/Coordinates.s"
	@echo "... src/MemoryPool.o"
	@echo "... src/MemoryPool.i"
	@echo "... src/MemoryPool.s"
	@echo "... tst/BasicMemoryPoolTest.o"
	@echo "... tst/BasicMemoryPoolTest.i"
	@echo "... tst/BasicMemoryPoolTest.s"
	@echo "... tst/MemoryPoolTestMultiThreading.o"
	@echo "... tst/MemoryPoolTestMultiThreading.i"
	@echo "... tst/MemoryPoolTestMultiThreading.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

